[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm ci --omit=dev --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build"
]

[phases.start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"
